modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/TwelveIterationMods/CraftingCraft/issues"

[[mods]]
modId="craftingcraft"
version="${file.jarVersion}"
displayName="CraftingCraft"
displayURL="https://blay09.net/mods/craftingcraft"
logoFile="craftingcraft-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
Adds an inventory crafting table and a normal portable one.
'''

[[dependencies.craftingcraft]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.craftingcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.craftingcraft]]
    modId="balm"
    mandatory=true
    versionRange="[5.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.craftingcraft]]
    modId="craftingtweaks"
    mandatory=false
    versionRange="[16,)"
    ordering="NONE"
    side="BOTH"